# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-31 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('screenshot', models.ImageField(default='photos/default.jpg', upload_to='photos/')),
                ('optional_screenshot', models.ImageField(default='photos/default.jpg', upload_to='photos/')),
                ('link', models.CharField(max_length=50)),
                ('technologies', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.Profile')),
            ],
        ),
    ]
