# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20190731_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='optional_screenshot',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
