# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20190801_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='optional_screenshot',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
    ]
